/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AllocationsIndexRouteImport } from './routes/allocations/index'
import { Route as CoursesIndexRouteImport } from './routes/courses/index'
import { Route as DepartmentsIndexRouteImport } from './routes/departments/index'
import { Route as ProfessorsIndexRouteImport } from './routes/professors/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AllocationsIndexRoute = AllocationsIndexRouteImport.update({
  id: '/allocations/',
  path: '/allocations/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesIndexRoute = CoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => rootRouteImport,
} as any)
const DepartmentsIndexRoute = DepartmentsIndexRouteImport.update({
  id: '/departments/',
  path: '/departments/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfessorsIndexRoute = ProfessorsIndexRouteImport.update({
  id: '/professors/',
  path: '/professors/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/allocations/': typeof AllocationsIndexRoute
  '/courses/': typeof CoursesIndexRoute
  '/departments/': typeof DepartmentsIndexRoute
  '/professors/': typeof ProfessorsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/allocations': typeof AllocationsIndexRoute
  '/courses': typeof CoursesIndexRoute
  '/departments': typeof DepartmentsIndexRoute
  '/professors': typeof ProfessorsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/allocations/': typeof AllocationsIndexRoute
  '/courses/': typeof CoursesIndexRoute
  '/departments/': typeof DepartmentsIndexRoute
  '/professors/': typeof ProfessorsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/allocations/' | '/courses/' | '/departments/' | '/professors/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/allocations' | '/courses' | '/departments' | '/professors'
  id:
    | '__root__'
    | '/'
    | '/allocations/'
    | '/courses/'
    | '/departments/'
    | '/professors/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AllocationsIndexRoute: typeof AllocationsIndexRoute
  CoursesIndexRoute: typeof CoursesIndexRoute
  DepartmentsIndexRoute: typeof DepartmentsIndexRoute
  ProfessorsIndexRoute: typeof ProfessorsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/allocations/': {
      id: '/allocations/'
      path: '/allocations'
      fullPath: '/allocations/'
      preLoaderRoute: typeof AllocationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/': {
      id: '/courses/'
      path: '/courses'
      fullPath: '/courses/'
      preLoaderRoute: typeof CoursesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/departments/': {
      id: '/departments/'
      path: '/departments'
      fullPath: '/departments/'
      preLoaderRoute: typeof DepartmentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/professors/': {
      id: '/professors/'
      path: '/professors'
      fullPath: '/professors/'
      preLoaderRoute: typeof ProfessorsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AllocationsIndexRoute: AllocationsIndexRoute,
  CoursesIndexRoute: CoursesIndexRoute,
  DepartmentsIndexRoute: DepartmentsIndexRoute,
  ProfessorsIndexRoute: ProfessorsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
